Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,18 +13,7 @@ jobs:
     - name: Check diff
       run: |
         # Get the differences between base and head branches
-        git fetch origin ${{ github.event.pull_request.base.ref }}
-        git fetch origin ${{ github.event.pull_request.head.ref }}
-        git merge --no-ff ${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }}
-        DIFF=$(git diff ${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }})
-        
-        # Check if 'automationId' is removed
-        if echo "$DIFF" | grep -q "automationId"; then
-          echo "No differences found between base and head branches, or 'automationId' text is removed."
-          exit 1
-        else
-          echo "Differences found between base and head branches, and 'automationId' text is not removed."
-          exit 0
-        fi
+          git diff --name-only ${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }} | xargs grep -L "automationId" || { echo "ERROR: 'automationId' text removed" && exit 1; }
 
+        
  
